### ISSUE TITLE
[Feature Request] Update a json5 file

### ISSUE THREAD

**Issue by tacman** [colinodell/json5#32] opened 2024-11-23 14:21 UTC
## Detailed description

I have some configuration files that are sometimes updated automatically.  Is there a way to read a JSON5 file, update some keys, then write it back out, including the comments?

What I'm thinking of is the ability to run a computer command (e.g. composer requires symfony/yaml), listen for the installation event, then update a composer.json5 file.  

I realize it's a long shot and not necessary in most cases, but I figured I'd ask.  It's so nice to have comments in JSON5!

**Comment by colinodell** [comment] 2024-11-25 11:31
Thanks for the suggestion!

I think this is a duplicate of #5?

Although I can certainly understand how nice this feature would be, it would require a significant rewrite of this library, so I don't have plans to implement this 😞

**Closed by colinodell** 2024-11-25 11:31 UTC
Labels: duplicate

**Comment by tacman** [comment] 2024-11-25 12:10
Makes sense.  It's almost impossible with YAML files as well.  Just not worth the effort.
